# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d2f4bf1d5a746b732cae639a5826858e9f5a44f9de8a709ecf0d566a05feb55bbe327f204c7b3099783ab56de9324438b34a0e9751cded0196e9c6b7065256

test:
  secret_key_base: d50f8ef7c9886e2d786d481647822c7ddf50955f66c20a9d1a35a3dc14f9d8067777cd965d7910b88dbf7507d79ee2261c65090b68822fb6d846a4453abd6d32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
